name: Keep App Alive

on:
  schedule:
    # 3時間おき（UTC）→ 日本時間 9:00, 12:00, 15:00, ...
    - cron: '0 */3 * * *'
  # 手動実行を可能にするトリガー
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App twice
        run: |
          curl --fail -s -o /dev/null https://app2dcolormap-6kdothisijw76lj7hyxl3n.streamlit.app/
          sleep 10
          curl --fail -s -o /dev/null https://app2dcolormap-6kdothisijw76lj7hyxl3n.streamlit.app/
