name: Keep App Alive

on:
  schedule:
    # 8時間おき（UTC 0, 8, 16時）→ 日本時間 9:00, 17:00, 1:00
    - cron: '0 */10 * * *'
  # 手動実行を可能にするトリガー
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Streamlit App
        run: |
          # 単に起こすだけなら HEAD リクエスト(-I)でもOK
          # 失敗したらジョブも失敗させたいなら --fail を付ける
          curl -I --fail https://calc-potolo-polus.streamlit.app/
